#:schema node_modules/wrangler/config-schema.json
account_id = "a004777392bb363fac2c1555755acee5"
name = "diplomatic-cloudflare-host"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DIP_DB"
database_name = "diplomatic"
database_id = "bba55e96-b690-4d86-9807-45bce967cfa6"
