#:schema node_modules/wrangler/config-schema.json
account_id = "a004777392bb363fac2c1555755acee5"
name = "sync-beta"
main = "src/index.ts"
compatibility_date = "2026-02-28"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "sync-beta.interncom.org"
zone_name = "interncom.org"
custom_domain = true

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServerV2"

[[migrations]]
tag = "v1"
new_classes = [ "WebSocketServer" ]

[[migrations]]
tag = "v2"
new_sqlite_classes = [ "WebSocketServerV2" ]
deleted_classes = [ "WebSocketServer" ]

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DIP_DB"
database_name = "diplomatic"
database_id = "936ba773-318d-4e12-a0ff-d74f95e20bbf"

[observability]
enabled = true
