// This file is used to augment the Env type with the one generated by `wrangler types`.
// Run `npm run cf-typegen` to regenerate worker-configuration.d.ts

/// <reference types="../worker-configuration.d.ts" />
