import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { printSizeBreakdown } from "./size-breakdown.mjs";

const verbose = process.argv.includes("--verbose");

// bun build cwd is repo root; printSizeBreakdown runs from pkg/
const webMetaFromRoot = "pkg/dist/web/index.meta.json";
const workerMetaFromRoot = "pkg/dist/web/worker.meta.json";
const webMetaFlag = verbose ? ` --metafile=${webMetaFromRoot}` : "";
const workerMetaFlag = verbose ? ` --metafile=${workerMetaFromRoot}` : "";

// 1) Bundle worker first (self-contained ESM for blob spawn).
execSync(
  `bun build --target browser --format esm --outfile pkg/dist/web/worker.mjs --minify${workerMetaFlag} web/src/worker/entry.ts`,
  { cwd: "..", stdio: "inherit" },
);
if (verbose) await printSizeBreakdown("dist/web/worker.meta.json", "web/worker.mjs");

// 2) Embed worker source (gitignored .ts under shared/worker) for blob spawn.
// Base64: bun --minify drops large string literals that look like JS (the raw
// worker.mjs text). Opaque base64 survives minify and is decoded in spawn.ts.
const embeddedPath = new URL(
  "../shared/worker/embeddedWorkerSource.ts",
  import.meta.url,
);
const workerJs = readFileSync(new URL("./dist/web/worker.mjs", import.meta.url), "utf8");
const workerB64 = Buffer.from(workerJs, "utf8").toString("base64");
const embedded = `// Generated by pkg/build-web.mjs — do not edit or commit.
export const DIPLOMATIC_WORKER_SOURCE_B64 = ${JSON.stringify(workerB64)};
`;
writeFileSync(embeddedPath, embedded);
if (verbose) {
  console.log(
    `embedded worker source: ${(workerJs.length / 1024).toFixed(1)} KB ` +
      `(${(workerB64.length / 1024).toFixed(1)} KB b64) → shared/worker/embeddedWorkerSource.ts`,
  );
}

// 3) Main library bundle (includes embedded worker string).
execSync(
  `bun build --target browser --format esm --outfile pkg/dist/web/index.mjs --external react --minify${webMetaFlag} web/src/index.ts`,
  { cwd: "..", stdio: "inherit" },
);
if (verbose) await printSizeBreakdown("dist/web/index.meta.json", "web/index.mjs");

// Fail the build if minify (or anything else) dropped the embed.
const indexJs = readFileSync(new URL("./dist/web/index.mjs", import.meta.url), "utf8");
if (workerB64.length > 0 && !indexJs.includes(workerB64.slice(0, 48))) {
  throw new Error(
    "build-web: embedded worker source missing from index.mjs " +
      "(bun minify may have dropped it; see base64 embed in this script)",
  );
}

// Restore empty stub so the tree stays free of the large worker string
// (real embed is already inlined into index.mjs).
writeFileSync(
  embeddedPath,
  `// Stub so the module always resolves for tsc / vitest.
// pkg/build-web.mjs overwrites this with the real worker base64 for the
// library bundle, then restores this stub. Do not put the real source in git.
export const DIPLOMATIC_WORKER_SOURCE_B64 = "";
`,
);

execSync("cd web && tsc --emitDeclarationOnly --outDir ../pkg/dist/web", {
  cwd: "..",
  stdio: "inherit",
});
