import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { printSizeBreakdown } from "./size-breakdown.mjs";

const verbose = process.argv.includes("--verbose");

// bun build cwd is repo root; printSizeBreakdown runs from pkg/
const webMetaFromRoot = "pkg/dist/web/index.meta.json";
const workerMetaFromRoot = "pkg/dist/web/worker.meta.json";
const webMetaFlag = verbose ? ` --metafile=${webMetaFromRoot}` : "";
const workerMetaFlag = verbose ? ` --metafile=${workerMetaFromRoot}` : "";

// 1) Bundle worker first (self-contained ESM for blob spawn).
execSync(
  `bun build --target browser --format esm --outfile pkg/dist/web/worker.mjs --minify${workerMetaFlag} web/src/worker/entry.ts`,
  { cwd: "..", stdio: "inherit" },
);
if (verbose) await printSizeBreakdown("dist/web/worker.meta.json", "web/worker.mjs");

// 2) Embed worker source (gitignored .ts under shared/worker) for blob spawn.
const embeddedPath = new URL(
  "../shared/worker/embeddedWorkerSource.ts",
  import.meta.url,
);
const workerJs = readFileSync(new URL("./dist/web/worker.mjs", import.meta.url), "utf8");
const embedded = `// Generated by pkg/build-web.mjs — do not edit or commit.
export const DIPLOMATIC_WORKER_SOURCE = ${JSON.stringify(workerJs)};
`;
writeFileSync(embeddedPath, embedded);
if (verbose) {
  console.log(
    `embedded worker source: ${(workerJs.length / 1024).toFixed(1)} KB → shared/worker/embeddedWorkerSource.ts`,
  );
}

// 3) Main library bundle (includes embedded worker string).
execSync(
  `bun build --target browser --format esm --outfile pkg/dist/web/index.mjs --external react --minify${webMetaFlag} web/src/index.ts`,
  { cwd: "..", stdio: "inherit" },
);
if (verbose) await printSizeBreakdown("dist/web/index.meta.json", "web/index.mjs");

// Restore empty stub so the tree stays free of the large worker string
// (real embed is already inlined into index.mjs).
writeFileSync(
  embeddedPath,
  `// Stub so the module always resolves for tsc / vitest.
// pkg/build-web.mjs overwrites this with the real worker.mjs string for the
// library bundle, then restores this stub. Do not put the real source in git.
export const DIPLOMATIC_WORKER_SOURCE = "";
`,
);

execSync("cd web && tsc --emitDeclarationOnly --outDir ../pkg/dist/web", {
  cwd: "..",
  stdio: "inherit",
});
