name: Style Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Run style checks
        run: ./style.sh